### ISSUE TITLE
Cake.Git 3.0.0

### ISSUE THREAD

**Issue by patriksvensson** [cake-contrib/Cake_Git#169] opened 2022-12-05 15:20 UTC
Would it be possible to release a `3.0.0` version of Cake.Git containing the latest changes?

**Comment by gep13** [comment] 2022-12-13 21:27
I think this is a duplicate of this: https://github.com/cake-contrib/Cake_Git/issues/168 so I am going to go ahead and close this out.

If I have missed something, let me know.

**Closed by gep13** 2022-12-13 21:27 UTC

**Comment by patriksvensson** [comment] 2022-12-14 00:41
#168 is closed, but no 3.0.0.

**Comment by augustoproiete** [comment] 2022-12-14 20:50
:tada: The changes implemented in response to this issue shipped with **Cake.Git v3.0.0**

The release is available on:

- :rocket: [GitHub Release](https://github.com/cake-contrib/Cake_Git/releases/tag/v3.0.0)
- :package: [NuGet Package](https://www.nuget.org/packages/Cake.Git/3.0.0)

**Comment by patriksvensson** [comment] 2022-12-14 23:31
Awesome! 🎉
