### ISSUE TITLE
Cake.Git v2.0.0 breaks IntelliSense in VS Code

### ISSUE THREAD

**Issue by KatoStoelen** [cake-contrib/Cake_Git#160] opened 2021-12-14 19:04 UTC
Originally posted here: cake-build/cake-vscode#614

Having an addin directive for `Cake.Git` v2.0.0 in a `.cake` file causes the following error when Omnisharp.Cake tries to load the file.

```csharp
#addin "nuget:?package=Cake.Git&version=2.0.0"
```

```console
[fail]: OmniSharp.Cake.CakeProjectSystem
        c:\path\to\workspace\build\build.cake will be ignored due to an following error
System.IO.FileNotFoundException: Cake is not installed. Path  does not exist.
   at OmniSharp.Cake.CakeProjectSystem.GetProject(CakeScript cakeScript, String filePath) in D:\a\1\s\src\OmniSharp.Cake\CakeProjectSystem.cs:line 281
   at OmniSharp.Cake.CakeProjectSystem.AddCakeFile(String cakeFilePath) in D:\a\1\s\src\OmniSharp.Cake\CakeProjectSystem.cs:line 125
```

Downgrading `Cake.Git` to 1.x.x solves the issue.

**Comment by nils-a** [comment] 2021-12-14 23:03
I think this is a regression from #158, specifically [adding the `runtimes`](https://github.com/cake-contrib/Cake_Git/pull/158/files#diff-c6eace5a70f0c2d920dfa97e988d4cad3d0131dd2b029bb2646c96222e866cf8R214) to the nupkg.

Specifically, removing the `tools/addins/Cake.Git.2.0.0/runtimes/win-x46` folder "fixes" the error. (When running on windows, that is...)
My feeling would be that having that dll twice in there throws off Cake.Bakery.
Could that be possible, @bjorkstromm ?

**Comment by bjorkstromm** [comment] 2021-12-15 20:09
> I think this is a regression from #158, specifically [adding the `runtimes`](https://github.com/cake-contrib/Cake_Git/pull/158/files#diff-c6eace5a70f0c2d920dfa97e988d4cad3d0131dd2b029bb2646c96222e866cf8R214) to the nupkg.
> 
> More specifically, removing the `tools/addins/Cake.Git.2.0.0/runtimes/win-x46` folder "fixes" the error. (When running on windows, that is...) My feeling would be that having that dll twice in there throws off Cake.Bakery. Could that be possible, @bjorkstromm ?

Cake.Bakery should ignore everything in `runtimes/` folder as these are not needed during compilation. Today, that might not be the case, since it's sharing NuGet logic with Cake (which needs stuff under `/runtimes`). Can we move this bug to `Cake.Bakery` repo?

**Comment by gep13** [comment] 2021-12-15 20:18
@bjorkstromm There already was an issue created in the bakery repository regarding this, and this issue was created afterwards. I would suggest closing this one and using the other.

**Comment by bjorkstromm** [comment] 2021-12-15 20:43
> @bjorkstromm There already was an issue created in the bakery repository regarding this, and this issue was created afterwards. I would suggest closing this one and using the other.

Wasn't it created in Cake-VSCode? E.g. this https://github.com/cake-build/cake-vscode/issues/614

**Comment by gep13** [comment] 2021-12-15 21:25
Doh! Sorry, you are right! That one we can move to bakery repository.

**Comment by gep13** [comment] 2021-12-15 21:27
@bjorkstromm I have moved the issue here: https://github.com/cake-build/bakery/issues/168

**Comment by bjorkstromm** [comment] 2021-12-15 21:40
> @bjorkstromm I have moved the issue here: https://github.com/cake-build/bakery/issues/168

Thanks @gep13! I'll go ahead and close this then.

**Closed by bjorkstromm** 2021-12-15 21:40 UTC
